# Session settings
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        name: JSESSIONID  # Custom name for the session cookie
        http-only: true   # Make the cookie HTTP-only to prevent client-side access
        secure: false      # Send cookie only over HTTPS (enable in production)
        path: /           # Path for the session cookie
      timeout: 1m        # Session timeout set to 30 minutes
logging:
  level:
    root: INFO
    com:
      app:
        controllers: DEBUG
        services: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 10

spring:
  threads:
    virtual:
      enabled: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 48210583b24f35
    password: 
    properties.mail.smtp:
      auth: true
      starttls.enable: true
application:
  jwt_config:
    issuer: MyStores
    secret: 
    access_exp_time: 1800 #Short-lived (e.g., 15 minutes, 1 hour).
    refresh_exp_time: 7776000000  #Stored securely on the client.
  vendor_config:
  customer_config:
    otp_verification_enabled: false
    verify_otp: false
    otp_exp_time: 60  #In seconds
    otp_no_of_retry: 3  #In seconds
    email_token_exp: 3600
    address_valid_keys:
      - address1
      - address2
      - city    
      - state
      - zipCode
      - state
      - country
  sms_api_config:
    api_key:
    route: q #otp q-->Quick SMS
    url:
    flash: 1